[package]
name = "pow_monitor"
version = "0.1.0"
edition = "2021"
description = "Sends a validator ready transaction to the Nimiq PoW chain and monitor this chain for validator readiness"

[dependencies]
nimiq_rpc = "0.1.2"
